import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import authStore from "@/lib/authStore.js";
import api from "@/lib/axiosRequestConfig.js";
import { useEffect } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const 
  useEffect(() => {
    const fetchUserDetails = async () => {
      try {
        const res = await api.get("/me");
        const userDetails = res.data;
        signIn(userDetails);
      } catch (err) {
        
      }
    };
    fetchUserDetails();
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
